### ISSUE TITLE
Any plan to release the code？

### ISSUE THREAD

**Issue by Doragd** [PluviophileYU/COSY#1]
Hi, thanks for your excellent work on multilingual NLP with causal inference.
I would like to know if there is a specific timeline to release the code ?

**Comment by PluviophileYU** [comment]
Hi Doragd, sorry for my delay. For now, I am busy with the internship for graduation T_T, thus the code is not cleaned yet. If you are urgent for the code, please leave your email or WeChat and I will send you the raw code instead. Thanks for your understanding!

**Comment by PluviophileYU** [comment]
Sorry for the delay. Recently I am during an internship for graduation T_T. I just updated a version of the code. Thanks for the understanding!
